CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP,
	username VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	hashed_password VARCHAR(255) NOT NULL,
	deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS posts (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP,
	content VARCHAR NOT NULL,
	author_id INTEGER
		REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP,
	content VARCHAR NOT NULL,
	author_id INTEGER
		REFERENCES users (id),
	post_id INTEGER
		REFERENCES posts (id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users (id),
	post_id INTEGER
		REFERENCES posts (id)
		ON DELETE CASCADE
);
